apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - podmonitor-kserve-predictors.yaml
  - servicemonitor-dcgm-exporter.yaml
  - servicemonitor-trustyai.yaml
  - prometheus-rules.yaml
  - alertmanager-config.yaml