apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # TODO: This part should be removed completely
  # as it is just a temp workaround. Normally it
  # should be covered by a slack app and not by
  # a proxy 
  - deployment.yaml
  - service.yaml
