apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - grafana
  - rhoai-models-registry
  # TODO: This part should be removed completely
  # as it is just a temp workaround. Normally it
  # should be covered by a slack app and not by
  # a proxy
  - slack-webhook-proxy
  - ai-providers